- name: Discord Message Notify
  uses: appleboy/discord-action@0.0.3
  with:
    # discord webhook id
    webhook_id: 766925294291648523
    # discord webhook token
    webhook_token: pu_sng014j64EicUIInOt5wAOgyfsk4yViLUe4HjCWn2MMiEtyYLvfcnC50J2Uhh5FYH
    # the message contents (up to 2000 characters)
    message: # optional
    # the contents of the file being sent
    file: # optional
    # color code of the embed
    color: # optional
    # waits for server confirmation of message send before response, and returns the created message body
    wait: # optional
    # true if this is a TTS message
    tts: # optional
    # override the default username of the webhook
    username: Uptimo
    # override the default avatar of the webhook
    avatar_url: # optional
